# TODO adapt to local environment
JAVA_HOME=/Users/vutran.kien/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
ANDROID_HOME=/Users/vutran.kien/Library/Developer/Xamarin/android-sdk-macosx
PATH=$PATH:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools
if [ -d ~/bin ]; then
	PATH=~/bin:$PATH
fi
SHELL_SESSION_HISTORY=0
EDITOR=vim

export ANDROID_HOME

# generated by Git for Windows
test -f ~/.profile && . ~/.profile
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
