# TODO adapt to local environment
JAVA_HOME=/Users/vutran.kien/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25
ANDROID_HOME=/Users/vutran.kien/Library/Developer/Xamarin/android-sdk-macosx
PATH=$PATH:$JAVA_HOME/bin:$ANDROID_HOME/platform-tools
if [ -d ~/bin ]; then
	PATH=~/bin:$PATH
fi
if [ -d ~/.local/bin ]; then
	PATH=~/.local/bin:$PATH
fi

SHELL_SESSION_HISTORY=0
EDITOR=vim

export ANDROID_HOME

# generated by Git for Windows
test -f ~/.profile && . ~/.profile

#export GTK_IM_MODULE=ibus
#export QT_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus

# Launch ssh-agent upon login
#ssh-add
# This file is sourced by bash for login shells.  The following line
# runs your .bashrc and is recommended by the bash info pages.
if [[ -f ~/.bashrc ]] ; then
	. ~/.bashrc
fi

#[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
